system_fcv/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/','HtmlController@home');

// Route::get('home',"HtmlController@home");

Route::get('freeassesment',"HtmlController@freeassesment");

Route::get('applycaips',"HtmlController@applycaips");

Route::get('aboutus',"HtmlController@aboutus");

Route::get('blog',"HtmlController@blog");

Route::get('blogapi',"HtmlController@blogapi");

Route::get('contactus',"HtmlController@contactus");

Route::post('caipsupload', "fileupload@fileupload");

Route::post('mail', "MailController@mail");

Route::resource('post','PostController');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/user/logout', 'Auth\LoginController@userLogout')->name('user.logout');

Route::prefix('admin')->group(function(){
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@loginout')->name('admin.logout');
});

Auth::routes();

system_fcv/app/Http/Controllers/HtmlController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Classes\base64images;
use Illuminate\Http\Request;

class HtmlController extends Controller
{
    public function home(){
        return view("html.home");
}

public function freeassesment(){
    return view("html.freeassesment");
}

public function applycaips(){
      $img = new base64images(); // object created
      $data = $img->imagedata(); // object is call public fucnction
     return view("html.applycaips",['data'=>$data]);
}
 public function aboutus(){
     return view("html.aboutus");
}


public function blogapi(Request $request){
$posts = post::all();

foreach($posts as $post){
    if(isset($post['image'])){
     $post['image'] = 'https://forcanadavisa.com'.$post['image'];
    }
} 
echo $posts;
}

 public function blog(){
     $posts = post::all();
     echo json_encode($posts);
}
 public function contactus(){
     return view("html.contactus");
}
}

system_fcv/resources/views/html/aboutus.blade.php
@extends("layout.html")

@section("title","About Us | Canda Visa")


@section("assesmentonly");

        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">
                        <div class="sidebar">
                            <div class="widget widget-quote-form bg-yellow">
                                <h3 class="form-title">Free Immigration Assessment</h3>
                                <p class="form-text">Find out your options for visa by completing a free online assessment.</p>
                                <form class="sidebar-quote-form" method="post" action="widget-enquiry.php">
                                     Text input
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="yourname">Your Name</label>
                                        <div class="">
                                            <input id="yourname" name="yourname" type="text" placeholder="Your Name" class="form-control" required="">
                                        </div>
                                    </div>
                                     Text input
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="email">Email</label>
                                        <div class="">
                                            <input id="email" name="email" type="email" placeholder="Email" class="form-control input-md" required="">
                                        </div>
                                    </div>
                                  
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="mobileno">Mobile No</label>
                                        <div class="">
                                            <input id="mobileno" name="mobileno" type="number" placeholder="Mobile No" class="form-control" required="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="selectvisa" class="sr-only">Select Visa</label>
                                        <select class="form-control" id="selectvisa" name="selectvisa">
                                            <option value="Select Visa">Select Visa</option>
                                            <option value="Students Visa">Students Visa</option>
                                            <option value="Business Visa">Business Visa</option>
                                            <option value="Family Visa">Family Visa</option>
                                            <option value="Travel Visa">Travel Visa </option>
                                            <option value="Work Visa">Work Visa </option>
                                            <option value="Visitor Visa">Visitor Visa </option>
                                            <option value="Migrate Visa">Migrate Visa </option>
                                            <option value="PR Visa">PR Visa</option>
                                        </select>
                                    </div>
                                    <!-- Textarea -->
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="message">Message</label>
                                        <div class="">
                                            <textarea class="form-control" id="message" name="message" rows="4" placeholder="Message"></textarea>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-default btn-lg btn-block">Book Free Assessment</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

system_fcv/resources/views/html/blog.blade.php
@extends("layout.html")

@section("title","Blog | Canada Visa")


@section("blog");
   
 <div class="container">
     
        @if(!empty($posts))
        <h2>Top 10 recent blogs</h2>
            @foreach($posts as $post) 
                <div class="well well-lg">
                    <h2>{{$post->title}}</h2>
                    <p>{{$post->body}}</p>
                    <p>Visit Count: {{$post->visit_count}}</p>
                    <p>Comment Count: {{$post->comment_count}}</p>
                    <p>Post Created At: {{date('F d,Y', strtotime($post->created_at))}} at {{date('g:ia',strtotime($post->created_at))}}</p>
                    <a href= "{{ route('post.show',$post->id) }}" class="btn btn-primary full-rigth">Read More</a>
                </div>
            @endforeach
        @endif    
    </div>


@endsection

system_fcv/resources/views/html/contactus.blade.php
@extends("layout.html")

@section("title","Contact | Canada Visa")


@section("assesmentonly");

        <div class="content">
            <div class="container">
                <div class="row">
                    <div class= "col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">

                        <h1>Here is a contact form for you. Please fill the form.</h1>
                        <div class="alert alert-danger " style=" margin:10px;">
                                <strong>Info! </strong>Email at: aesha@forcanadavisa.com (OR) Fill the contact Form.
                            </div>

                            <div class="alert alert-info " style=" margin:10px;">
                                <strong>Info!</strong> Our officers might be engaged with case studies ,we will try to contact as soon as possible.
                            </div>
                        <p><br><br>

                        This visa check is for people who would live and work in Canada temporarily or permanently. Do you intend to run a business in Canada? Then please fill out the visa check for business purposes.
                        How does it work?<br><br>

                        Please fill out the form below if you are searching for an advice on your visa options for Canada. Based on the information you provide in the visa check form, our visa consultants will assess your profile and therewith your visa options. Please note that this is not an automated process, therefore it could take some time to assess your profile.

                        <br><br>
                        </p>
                            <div class="alert alert-success">
                                <strong>Success!</strong> our consultants will contact you by phone or e-mail to provide you with an advice.
                                        Please keep an eye on your ‘spam-box’. It might happen that our e-mails are received there.
                            </div> 
                    </div>



                    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
                    @if($message = Session::get('success'))
                                <div class="alert alert-sucess">
                                    <h3>Notice:<br> {{$message}}</h3>
                                </div>
                            @endif
                        <div class="sidebar">
                            <div class="widget widget-quote-form bg-yellow">
                                <h3 class="form-title">Contact Form</h3>

                                <p class="form-text">Submit the form we will contact you shortly.</p>
                                <form class="sidebar-quote-form" method="post" action="{{url('/mail')}}">
                                {{csrf_field()}}
                                     Name :
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="yourname">Your Name</label>
                                        <div class="">
                                            <input id="yourname" name="yourname" type="text" placeholder="Your Name" class="form-control" required="">
                                        </div>
                                    </div>
                                     Email :
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="email">Email</label>
                                        <div class="">
                                            <input id="email" name="email" type="email" placeholder="Email" class="form-control input-md" required="">
                                        </div>
                                    </div>
                                  Contact No:
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="mobileno">Mobile No</label>
                                        <div class="">
                                            <input id="mobileno" name="mobileno" type="number" placeholder="Mobile No" class="form-control" required="">
                                        </div>
                                    </div>
                                    Visa Type:
                                    <div class="form-group">
                                        <label for="selectvisa" class="sr-only">Select Visa</label>
                                        <select class="form-control" id="selectvisa" name="selectvisa">
                                            <option value="Select Visa">Select Visa</option>
                                            <option value="Students Visa">Students Visa</option>
                                            <option value="Business Visa">Business Visa</option>
                                            <option value="Family Visa">Family Visa</option>
                                            <option value="Travel Visa">Travel Visa </option>
                                            <option value="Work Visa">Work Visa </option>
                                            <option value="Visitor Visa">Visitor Visa </option>
                                            <option value="Migrate Visa">Migrate Visa </option>
                                            <option value="PR Visa">PR Visa</option>
                                        </select>
                                    </div>
                                    Message :
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="message">Message</label>
                                        <div class="">
                                            <textarea class="form-control" id="message" name="message" rows="4" placeholder="Message"></textarea>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-default btn-lg btn-block">Submit Contact Form</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

system_fcv/resources/views/html/freeassesment.blade.php
@extends("layout.html")

@section("title","Free Assesment | Canada Visa")


@section("assesmentonly");

        <div class="content">
            <div class="container">
                <div class="row">
                    <div class= "col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">

                        <h1>A free assessment of your visa options with our visa check for Canada</h1>
                       
                            <div class="alert alert-info " style=" margin:10px;">
                                <strong>Info!</strong> Are you dreaming of a future in Canada? Start your adventure by filling out our free and non-binding visa check.
                        For who?
                            </div>
                        <p><br><br>

                        This visa check is for people who would live and work in Canada temporarily or permanently. Do you intend to run a business in Canada? Then please fill out the visa check for business purposes.
                        How does it work?<br><br>

                        Please fill out the form below if you are searching for an advice on your visa options for Canada. Based on the information you provide in the visa check form, our visa consultants will assess your profile and therewith your visa options. Please note that this is not an automated process, therefore it could take some time to assess your profile.

                        <br><br>
                        </p>
                            <div class="alert alert-success">
                              <strong>Success!</strong> Once an assessment is made, our consultants will contact you by phone or e-mail to provide you with an advice.
                                    Please keep an eye on your ‘spam-box’. It might happen that our e-mails are received there.
                            </div> 
                    </div>

                    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
                    @if($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <strong>Notice:</strong> {{$message}}
                                </div>
                            @endif
                        <div class="sidebar">
                            <div class="widget widget-quote-form bg-yellow">
                                <h3 class="form-title">Free Immigration Assessment</h3>

                                <p class="form-text">Find out your options for visa by completing a free online assessment.</p>
                                <form class="sidebar-quote-form" method="post" action="/mail">
                                {{csrf_field()}}
                                     Name :
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="yourname">Your Name</label>
                                        <div class="">
                                            <input id="yourname" name="yourname" type="text" placeholder="Your Name" class="form-control" required="">
                                        </div>
                                    </div>
                                     Email :
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="email">Email</label>
                                        <div class="">
                                            <input id="email" name="email" type="email" placeholder="Email" class="form-control input-md" required="">
                                        </div>
                                    </div>
                                  Contact No:
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="mobileno">Mobile No</label>
                                        <div class="">
                                            <input id="mobileno" name="mobileno" type="number" placeholder="Mobile No" class="form-control" required="">
                                        </div>
                                    </div>
                                    Visa Type:
                                    <div class="form-group">
                                        <label for="selectvisa" class="sr-only">Select Visa</label>
                                        <select class="form-control" id="selectvisa" name="selectvisa">
                                            <option value="Select Visa">Select Visa</option>
                                            <option value="Students Visa">Students Visa</option>
                                            <option value="Business Visa">Business Visa</option>
                                            <option value="Family Visa">Family Visa</option>
                                            <option value="Travel Visa">Travel Visa </option>
                                            <option value="Work Visa">Work Visa </option>
                                            <option value="Visitor Visa">Visitor Visa </option>
                                            <option value="Migrate Visa">Migrate Visa </option>
                                            <option value="PR Visa">PR Visa</option>
                                        </select>
                                    </div>
                                    Message :
                                    <div class="form-group">
                                        <label class="control-label sr-only" for="message">Message</label>
                                        <div class="">
                                            <textarea class="form-control" id="message" name="message" rows="4" placeholder="Message"></textarea>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-default btn-lg btn-block">Book Free Assessment</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

system_fcv/resources/views/html/singleblog.blade.php
<div class="container">
    <div class="row">
        <a href="{{url('/blog')}}">Go Back Home</a>
    </div>
</div>

<div class="container">
    <div class="row">
        <h1>{{$post->title}}</h1>
        <p>{{$post->body}}</p>
    </div>
</div>

<span class="fb-comments-count" data-href="{{ Request::url()}}"></span>
<!-- this need to be after body tag -->
<!-- facebook comment plugins -->
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v7.0&appId=259676348450816&autoLogAppEvents=1" nonce="8M0EpPRs"></script>
 
<!-- this need to be after body tag -->
<div class="fb-comments" data-href="http://127.0.0.1:8000/post/1" data-numposts="10" data-width=""></div>
<!-- <div class="fb-comments" data-href="http://127.0.0.1:8000/post/{{$id}}" data-numposts="10" data-width=""></div> -->