system_fcv/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/','HtmlController@home');

// Route::get('home',"HtmlController@home");

Route::get('freeassesment',"HtmlController@freeassesment");

Route::get('applycaips',"HtmlController@applycaips");

Route::get('aboutus',"HtmlController@aboutus");

Route::get('blog',"HtmlController@blog");

Route::get('blogapi',"HtmlController@blogapi");

Route::get('contactus',"HtmlController@contactus");

Route::post('caipsupload', "fileupload@fileupload");

Route::post('mail', "MailController@mail");

Route::resource('post','PostController');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/user/logout', 'Auth\LoginController@userLogout')->name('user.logout');

Route::prefix('admin')->group(function(){
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@loginout')->name('admin.logout');
});

Auth::routes();

system_fcv/resources/views/adminPanel/create.blade.php
@extends('layout.templateadmincontrol')

@section('title','CanadaVisa | Add Blog')

@section("head_section")
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
@endsection

@section('content')
<script>
        tinymce.init({
        selector: '#mytextarea',
        height: 400,
        width : 900,
        theme: 'modern',
        plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount  imagetools  contextmenu colorpicker textpattern help',
        toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
        image_advtab: true,
        templates: [
            { title: 'Test template 1', content: 'Test 1' },
            { title: 'Test template 2', content: 'Test 2' }
        ],
        content_css: [
            '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
            '//www.tinymce.com/css/codepen.min.css'
        ]
        });
  </script>

<h1>Add New Post</h1>
<div class="col-sm-8 col-sm-offset-2">
    <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
    @csrf
        <div class="form-group">
            <label for="title">Title:</label>
            <input name="title" type="text" class="form-control">
            </div>
        <div class="form-group">
            <input type="file" name="image" />
        </div>
      
        <div class="form-group">
            <label for="body">Body:</label>
           <textarea name="body" id="mytextarea"  class="form-control"></textarea>
        </div>
        <button type="submit" class="submit btn btn-primary" >Submit</button>
        <a href="{{ route('post.index') }}" class="btn btn-default pull-rigth">Go Back</a>

    </form>
</div>

@endsection

system_fcv/resources/views/adminPanel/editblog.blade.php
@extends('layout.templateadmincontrol')

@section('title','CanadaVisa | Edit Blog')

@section("head_section")
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
@endsection

@section('content')

  <script>
        tinymce.init({
        selector: '#mytextarea',
        height: 400,
        width : 900,
        theme: 'modern',
        plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount  imagetools  contextmenu colorpicker textpattern help',
        toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
        image_advtab: true,
        templates: [
            { title: 'Test template 1', content: 'Test 1' },
            { title: 'Test template 2', content: 'Test 2' }
        ],
        content_css: [
            '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
            '//www.tinymce.com/css/codepen.min.css'
        ]
        });
  </script>

<h1>Edit New Post : {{ $post->id ?? ' '}}</h1>
<div class="col-sm-8 col-sm-offset-2">
    <form action="{{ route('post.update', $post->id ) }}" method="post">
    @csrf
    <input type="hidden" name="_method" value="PUT">
        <div class="form-group">
            <label for="title">Title:</label>
            <input name="title" type="text" class="form-control" value = "{{$post->title ?? ' '}}">
        </div>

        <div class="form-group">
            <label for="body">Body:</label>
           <textarea name="body" id="mytextarea" cols="30" rows="10" class="form-control">{{$post->body ?? ' '}}</textarea>
        </div>
        <button type="submit" class="submit btn btn-primary">Submit</button>
        <a href="{{ route('post.index') }}" class="btn btn-default pull-rigth">Go Back</a>

    </form>
</div>

@endsection

system_fcv/resources/views/adminPanel/home.blade.php
@extends('layout.templateadmincontrol')


@section('title','Canada Visa | Admin Control')

@section("content")
<h1>Admin control Panel</h1>
@if($message = Session::get('success'))
    <div class="alert alert-sucess">
        <p>{{$message}}</p>
    </div>
@endif
@if($errors->any())
 <div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{$error}} </li>
        @endforeach
    </ul>
 </div>
@endif

<a href="{{ route('post.create') }}" class="btn btn-primary pull-rigth">Add New post</a>
<table class="table">
    <thead>
        <th>id</th>
        <th>title</th>
        <th>body</th>
        <th>edit</th>
        <th>remove</th>
    </thead>
    <tbody>
    @foreach($posts as $post)
    <tr>
        <th>{{$post->id ?? ''}}</th>
        <td>{{$post->title ?? ''}}</td>
        <td>{{$post->body ?? ''}}</td>
        <td>
            <a href="{{ route('post.edit', $post->id)}}" class="btn btn-primary">Edit</a>
        </td>
        <td>
            <form action="{{ route('post.destroy',$post->id )}}" method="post">
                @csrf
                <input type="hidden" name="_method" value="DELETE">
                <input class="btn btn-danger" type = "submit" value="Delete">
            </form>
        </td>
        </tr>
        @endforeach
    </tbody>
</table>


@endsection